config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'
  resources :posts do
    resources :comments, only: [:create, :destroy]
    end
  resources :blogs
  resources :users, only: [:show, :edit, :update] do
    resources :events 
      end
    end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord

  belongs_to :user


  validates :title,   length: { maximum: 20 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user 
  has_many :comments
  
 
  rescue => exception
    

  validates :content, presence: true, unless: :image?
  validates :text,  presence: true
  
  
  mount_uploader :image, ImageUploader
end

app/models/show.rb
class Show < ApplicationRecord
  # belongs_to :post 
  # belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
   validates :name, presence: true, uniqueness: true

   has_many :posts
   has_many :events
   has_many :comments
   has_many :blogs

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  def index
    @blogs = Blog.includes(:user)
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.create(blog_params)
    redirect_to blogs_path
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    blog = Blog.find(params[:id])
    blog.update(blog_params)
    redirect_to blog_path(blog.id)
    end

  def destroy
    blog = Blog.find(params[:id])
    blog.destroy
    redirect_to blogs_path
  end

  private
  def blog_params
    params.require(:blog).permit(:title, :content, :image).merge(user_id: current_user.id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def create
    Comment.create(comment_params)
    redirect_to post_path(params[:post_id])
  end


  def destroy
    comment = Comment.find(params[:post_id])
    - if current_user.id == comment.user.id
          comment.destroy
          redirect_to post_path
      end
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, post_id: params[:post_id])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy] #パラメータのidからレコードを特定するメソッド


  def index
    @events = Event.all.includes(:user)

    respond_to do |format|
      format.html
      format.json { render :json => @events }
    end
  end
 
  def show
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
      respond_to do |format|
        if @event.save
          format.html { redirect_to @event, notice: 'Event was successfully created.' }
          format.json { render :show, status: :created, location: @event }
        else
          format.html { render :new }
          format.json { render json: @event.errors, status: :unprocessable_entity }
        end
      end
  end

  

  def update
    event = Event.find(params[:id])
    @events = Event.where(user_id: current_user.id)
    event.update(event_params)
  end

  def destroy
    @user = User.find(params[:id])
    event = Event.find(params[:id])
    event.destroy
    # redirect_to user_path(@user)
  end

  private
  def event_params
    params.require(:event).permit(:title, :text, :start_date, :end_date)
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # before_action :post_group_by
  def index
    @posts = Post.all.includes(:user, :event)
    @posts = Post.all.order(id: :DESC)

  end

  def new
    @posts = Post.all.order(id: :DESC)
    @post = Post.new
    @posts = Post.includes(:user)
    @events = Event.includes(:event)
    @event = Event.new
    
    
    
  end

  def create

    @post = Post.create(post_params)
    # logger.debug @post.errors.inspect
      if @post.save
          respond_to do |format|
          # format.html { redirect_to new_post_path}
          format.json 
        end
      end
    @event = Event.create
        if @event.save
            respond_to do |format|
            format.json
          end
        end
  end

  def show
    @post = Post.find(params[:id]) 
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
    
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to new_post_path
  end


  private
  def post_params
    params.require(:post).permit(:text, :content, ).merge(user_id: current_user.id)
  end

  

  # def post_group_by
  #   @posts = Post.order('created_at DESC').group_by{|post| post.created_at.to_date.strftime('%Y/%m/%d')}
  #   gon.posts_group_by = @posts
  #   @users = User.all
  #   gon.users = []
  #   @users.each do |users|
  #     gon.users << users
  #   end
  # end

end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController

  # def index
  # end

  # def show
  #   @show = Post.find(params[:post_id]) 
  # end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def show
    @user = current_user.name
    @posts = current_user.posts
    @blogs = current_user.blogs
  end

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.haml
= form_with model: @blog, class: :form, local: true do |form|
    = form.text_field :title, placeholder: :"title", class: :form__title
    = form.text_area :content, placeholder: :"blog-main", class: :form__text
    = form.submit 'Create', class: :btn

app/views/blogs/edit.html.haml
.new-blog
  .new-blog__title
    Content changes?

  = render 'form'

app/views/blogs/index.html.haml
.blog-list
  .blog-create
    = link_to "junp to Create Blog", new_blog_path
  .blog-content
    - @blogs.each do |blog|
      .content
        = link_to blog_path(blog.id), class: "lists" do
          .content__left
            .content__left--image
              = blog.user.name
          .content__right
            .content__right__top
              = blog.title
            .content__right__bottom
              .content__right__bottom--date
                = blog.created_at.strftime("%Y年%m月%d日 %H時%M分")

app/views/blogs/new.html.haml
.new-blog
  .new-blog__title
    Create of new Blog

  = form_with model: @blog, class: :form, local: true do |form|
    = form.text_field :title, placeholder: :"title", class: :form__title
    = form.text_area :content, placeholder: :"blog-main", class: :form__text
    = form.submit 'Create', class: :btn

app/views/blogs/show.html.haml
.blog-show
  .blog-show-list
    .blog-title
      = @blog.title
    .blog-date
      = @blog.created_at.strftime("%Y年%m月%d日 %H時%M分")
      = link_to 'back', blogs_path, class: "blog-back-btn"
      - if current_user.id == @blog.user_id  
        = link_to 'edit', edit_blog_path(@blog.id), class: "blog-edit-btn"
        = link_to 'delete', blog_path(@blog.id), method: :delete, class: "blog-delete-btn"
    .blog-author
      .blog-text
        = simple_format @blog.content

app/views/events/_form_new.html.haml
h1 新規イベント追加
= form_with model: event, url: new_post_path do |f|
  -# = render "devise/shared/error_messages", resource: f.object
  .form-group
    = f.label :title
    = f.text_field :title, class:'form-control mb-3', required: true
  .form-group
    = f.label :start_time
    br
    = f.datetime_select :start_time, {default: Date.today + 19.hours + 00.minutes, minute_step: 10}, class:'form-control bootstrap-date mb-3'
  .form-group
    = f.label :description
    = f.text_area :text, class:'form-control mb-3'
  .actions
    = f.submit class: "btn btn-primary mb-3 js-event-create-btn"

app/views/events/index.html.haml
.calendar-index
  #calendar

app/views/posts/_post.html.haml
.main-list
  .main-list-user
    = post.user.name
  .main-list__text
    = link_to post_path(post.id) do
      .main-list__text__form
        text :
        = post.text
      .main-list__content
        content :
        = post.content
  .main-list__day
    = post.created_at.strftime("%Y年%m月%d日 %H時%M分")
    - if current_user.id == post.user_id
      = link_to "Delete", post_path(post.id), method: :delete, class: "delete-btn" 
  

app/views/posts/index.html.haml
.top-page
  = video_tag("/videos/video.mp4", autoplay: true, loop: true, muted: true, class: 'content__box__video')

  .start-btn
    .top-blog-btn
      = link_to "blogs", blogs_path
    .top-btn
      = link_to "posts", new_post_path
    .center-btn
      = link_to "WelCom", user_path(current_user.id)
  

  
  

app/views/posts/new.html.haml
.contents
  .left
    .left-header
      .left-username
        user name :     
        = current_user.name
      .left-edit
        = link_to "edit", edit_user_path(current_user), class: "edit-btn" 
    
    .left__list
    = form_with(model: @post, class: :form, local: true, id: :new_post) do |form|
      .left-form
        = form.text_field :text, placeholder: :text, class: :form__title
        = form.text_area :content, placeholder: :content, class: :form__text
      = form.submit 'Makeit', class: :form__btn
  .main
    .main__lists
      = render @posts
  .right
    .right__lists
      #calendar
        -# = form_with model: @event, class: :event_form, local: true, id: :new_event, url: :new_post  do |f|
        -#   -# = render "devise/shared/error_messages", resource: f.object
        -#   .form-group
        -#     = f.label :title
        -#     = f.text_field :title, class:'form-control mb-3', required: true
        -#   .form-group
        -#     = f.label :start_time
        -#     br
        -#     = f.datetime_select :start_time, {default: Date.today + 19.hours + 00.minutes, minute_step: 10}, class:'form-control bootstrap-date mb-3'
        -#   .form-group
        -#     = f.label :description
        -#     = f.text_area :text, class:'form-control mb-3'
        -#   .actions
        -#     = f.submit class: "btn btn-primary mb-3 js-event-create-btn"

app/views/posts/show.html.haml
.post-show  
  .post-show-list
    .post-btn
      = link_to "back", new_post_path, class: "back-btn" 
      - if current_user.id == @post.user_id
        = link_to "Delete", post_path(@post.id), method: :delete, class: "delete-btn" 
    .posts-show-day
      = @post.created_at.strftime("%Y年%m月%d日 %H時%M分")
    .posts-show-text
      content  :
      .posts-contents
        = @post.content
  .container_comments
    .comments
      %h4 ＜Comments all＞
      - if @comments
        - @comments.each do |comment|
          .comments-list
            .comment
              = link_to comment.user.name, "/users/#{comment.user_id}"
              ：
              = comment.text
            .delete-btn
              - if current_user.id == comment.user_id
                = link_to "Delete", post_comment_path(@post.comments.ids), method: :delete



    .container
      - if current_user
        = form_with(model: [@post, @comment], local: true) do |form|
          = form.text_area :text, placeholder: "comments", rows: "2", class: "form"
          = form.submit "Send", class: "btn"
      - else
        %strong
          %p ※※※ コメントの投稿には新規登録/ログインが必要です ※※※
    

app/views/shows/_show.html.haml
-# - @.each do |post| 
-#   .posts-show-day
-#     = post.created_at.strftime("%Y年%m月%d日 %H時%M分")
-#   .posts-show-text
-#     title  :
-#     = post.text
-#     .posts-show-content
-#       content  :
-#       = post.content
    


 

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      
      = link_to "log out", destroy_user_session_path, method: :delete, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'

app/views/users/show.html.haml
.post-title
  .post-name
    = current_user.name 
    's my-page
  .post-blog-btn
    .post-backbtn
    = link_to "Posts", new_post_path, class: "back-btn" 
    .blog-backbtn
    = link_to "Blogs", blogs_path, class: "blogs-btn" 
  .blog-post
    .post-content
      - @posts.each do |post|
        .content
          .content__left
            .content__left__text
              = link_to post_path(post.id), class: "content__right__top--title" do
                title :
                = post.text 
                .content__left__text__content
                content :
                = post.content
            .content__left__bottom
              .content__left__bottom__date
                = post.created_at.strftime("%Y年%m月%d日 %H時%M分")
              .post-btn
                - if current_user.id == post.user_id
                  = link_to "Delete", post_path(post.id), method: :delete, class: "delete-btn" 
    .blog-content
      - @blogs.each do |blog|
        .content
          .content__right
            .content__right__text
              = link_to blog_path(blog.id), class: "content__right__top--title" do
                title :
                = blog.title 
                .content__right__text__content
            .content__right__bottom
              .content__right__bottom__date
                = blog.created_at.strftime("%Y年%m月%d日 %H時%M分")
              .post-btn
                - if current_user.id == blog.user_id
                  = link_to "Delete", blog_path(blog.id), method: :delete, class: "delete-btn" 